name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: PWABuilder Action
        uses: pwa-builder/pwabuilder-action@v1
        with:
          pwa-url: "https://hmchoik915.github.io/car-log/"
          output-dir: "apk-output"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: apk-output/*.apk
